[build]
environment = { SECRETS_SCAN_OMIT_KEYS = "VITE_ANCHOR_DATE,VITE_CHAPCOUNT,VITE_COUNT" }
  command = "npm run build" 
  publish = "dist"  

functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200